"""roles table

Revision ID: d500f032b667
Revises: 
Create Date: 2023-01-04 10:50:26.027899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd500f032b667'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('atf_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('position', sa.String(length=300), nullable=False),
    sa.Column('department', sa.String(length=300), nullable=False),
    sa.Column('reports_to', sa.String(length=300), nullable=False),
    sa.Column('job_location', sa.String(length=300), nullable=False),
    sa.Column('grade', sa.String(length=300), nullable=False),
    sa.Column('number', sa.String(length=10), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('job_description', sa.Text(), nullable=True),
    sa.Column('job_content', sa.Text(), nullable=True),
    sa.Column('job_document_name', sa.String(length=300), nullable=True),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_due_date'), ['due_date'], unique=False)

    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_fullname', sa.String(length=500), nullable=False),
    sa.Column('role_shortcut', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_fullname')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=500), nullable=False),
    sa.Column('profile_pic', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=160), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('firstname', sa.String(length=500), nullable=True),
    sa.Column('lastname', sa.String(length=500), nullable=True),
    sa.Column('verification', sa.String(length=20), nullable=True),
    sa.Column('organization', sa.String(length=15), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('roles')
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_due_date'))

    op.drop_table('job')
    # ### end Alembic commands ###
